spring:
  profiles: dev
  datasource:
    password: pgadmin
    url: jdbc:postgresql://localhost:5432/tema_pcj
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL12Dialect
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8081
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace
management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
   
